name: Build and test

on: pull_request

permissions:
  pull-requests: write
  issues: write
  repository-projects: write

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "12"
      - name: tests
        id: test_output
        run: |
          npm install
          npm run test
          echo "status=${{ job.status }}" >> $GITHUB_OUTPUT

  test_success:
    name: tests successful
    permissions: write-all
    runs-on: ubuntu-latest
    needs: tests
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v1.1.1
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Enable auto-merge for Dependabot PRs
        # if: ${{contains(steps.metadata.outputs.dependency-names, 'my-dependency') && steps.metadata.outputs.update-type == 'version-update:semver-patch'}}
        run: |
          gh pr merge --auto --merge "$PR_URL"
          echo "status=${{needs.tests.steps.test_output.status}}"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: slack success notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{secrets.SLACK_WEBHOOK}}
          SLACK_MESSAGE: "${{GITHUB_REPOSITORY}} was updated successfully."
          SLACK_USERNAME: "Dependabot"
          SLACK_ICON: "https://avatars.githubusercontent.com/u/27347476?s=200&v=4"
          MSG_MINIMAL: commit