name: Build and test

on: pull_request

permissions:
  pull-requests: write
  issues: write
  repository-projects: write

jobs:
  tests:
    runs-on: ubuntu-latest
    permissions: write-all
    outputs:
      status: ${{steps.test_output.status}}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "12"
      - name: Run tests
        run: |
          npm install
          npm run test
      - name: Get github token
        if: ${{ github.actor == 'dependabot[bot]' && job.status == 'success' }}
        uses: dependabot/fetch-metadata@v1.1.1
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Merge dependabot PR
        if: ${{ github.actor == 'dependabot[bot]' && job.status == 'success' }}
        run: gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Notify slack on success
        uses: rtCamp/action-slack-notify@v2
        if: ${{ github.actor == 'dependabot[bot]' && job.status == 'success' }}
        env:
          SLACK_WEBHOOK: ${{secrets.SLACK_WEBHOOK}}
          SLACK_MESSAGE: "${{github.event.repository.name}} was updated successfully."
          SLACK_USERNAME: "Dependabot"
          SLACK_ICON: "https://avatars.githubusercontent.com/u/27347476?s=200&v=4"
          MSG_MINIMAL: commit
      - name: Notify slack on failure
        uses: rtCamp/action-slack-notify@v2
        if: ${{ github.actor == 'dependabot[bot]' && job.status == 'failure' }}
        env:
          SLACK_WEBHOOK: ${{secrets.SLACK_WEBHOOK}}
          SLACK_MESSAGE: "${{github.event.repository.name}} was not updated due to failing tests."
          SLACK_COLOR: "#FF0000"
          SLACK_USERNAME: "Dependabot"
          SLACK_ICON: "https://avatars.githubusercontent.com/u/27347476?s=200&v=4"
          MSG_MINIMAL: commit
